# Generated by Django 5.0.3 on 2024-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='audio',
            field=models.BooleanField(default=False, null=True, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='media',
            name='callback',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Callback'),
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category_two'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='subcategory_one',
            field=models.CharField(default=False, max_length=100, verbose_name='Subcategory_one'),
        ),
        migrations.AlterField(
            model_name='media',
            name='subcategory_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategory_two'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
    ]
