# Generated by Django 5.1b1 on 2024-08-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranAudioPhotoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Tartib raqam')),
                ('sura_name', models.CharField(max_length=60, verbose_name='Sura nomi')),
                ('total_verses', models.IntegerField(verbose_name='Oyatlar soni')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('zip', models.CharField(blank=True, max_length=200, null=True, verbose_name='ZIP ID')),
                ('audio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Audio ID')),
                ('photo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Photo ID')),
                ('docs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Document ID')),
            ],
            options={
                'verbose_name': "Qur'oni Karim",
                'verbose_name_plural': "Qur'oni Karim",
            },
        ),
    ]
