# Generated by Django 5.1b1 on 2024-08-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quranapds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuranAudioPhotoDoc',
            new_name='QuranAPD',
        ),
    ]
