# Generated by Django 5.1b1 on 2024-08-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranapds', '0002_rename_quranaudiophotodoc_quranapd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranapd',
            name='sequence',
            field=models.CharField(max_length=3, verbose_name='Tartib raqam'),
        ),
    ]
