# Generated by Django 5.1b1 on 2024-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranapds', '0003_alter_quranapd_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quranapd',
            name='audio',
        ),
        migrations.AddField(
            model_name='quranapd',
            name='audiohusary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Husary Audio ID'),
        ),
        migrations.AddField(
            model_name='quranapd',
            name='audiomuqriy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Muqriy Audio ID'),
        ),
    ]
