# Generated by Django 5.1b1 on 2024-08-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_rename_quranverseqoriphoto_quranvqp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Tartib raqam')),
                ('sura_name', models.CharField(max_length=60, verbose_name='Sura nomi')),
                ('total_verses', models.IntegerField(verbose_name='Oyatlar soni')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('zip', models.CharField(max_length=200, verbose_name='ZIP ID')),
                ('audio', models.CharField(max_length=200, verbose_name='Audio ID')),
                ('photo', models.CharField(max_length=200, verbose_name='Photo ID')),
                ('video', models.CharField(max_length=200, verbose_name='Video ID')),
                ('docs', models.CharField(max_length=200, verbose_name='Document ID')),
            ],
            options={
                'verbose_name': "Qur'oni Karim",
                'verbose_name_plural': "Qur'oni Karim",
            },
        ),
        migrations.DeleteModel(
            name='QuranVQP',
        ),
    ]
